JNI and Service implementation
StanislavShchyrba/Android-Servises pull request #2
Opened 2020-09-16 10:34 UTC by StanislavShchyrba

2020-09-16 12:11 UTC, gutachkee requested changes
It has 224 files to be reviewed :scream_cat:

Learn about .gitignore, add & apply proper gitignore file to the commit.

2020-09-18 13:24 UTC, gutachkee requested changes
1. Try to do not include not related changes into single commit or even pull request.
For example, right now we have "JNI and Service implementation" PR title, which means that this PR should contain changes related to impl of Service & JNI calls. But this PR contain IMyAidl.aidl file which has nothing to do with your task (since it contain method from the sample). 
2. Formatting: do self review, remove unnecessary newlines, think more on names you give for methods & variables. 

In general: great progress. Keep going on!

2020-09-18 13:24 UTC, gutachkee commented on src/main/cpp/native-lib.cpp
> +
Keep file well formatted.
```suggestion
```

2020-09-18 13:24 UTC, gutachkee commented on src/main/cpp/native-lib.cpp
> +
unnecessary newline.

2020-09-18 13:24 UTC, gutachkee commented on src/main/cpp/native-lib.cpp
> +        arr[i] = output[i];
Move out

2020-09-18 13:24 UTC, gutachkee commented on src/main/cpp/native-lib.cpp
> +        ++count[arr[i]];
Always use brackets
```suggestion
    for (i = 0; arr[i]; ++i) {
        ++count[arr[i]];
    }
```

2020-09-18 13:24 UTC, gutachkee commented on src/main/java/com/example/test/MainActivity.java
> +    public static final int SIZE_OF_RECYCLER_ELEMENTS = 100;
Combine related fields (I meant by removing newlines)
At least, all views can be combined.

2020-09-18 13:24 UTC, gutachkee commented on src/main/java/com/example/test/MainActivity.java
> +        mSpinner.setOnItemSelectedListener(this);
initSpinner()

2020-09-18 13:24 UTC, gutachkee commented on src/main/java/com/example/test/MainActivity.java
> +        mNumberList.setLayoutManager(NumberListManager);
initRecyclerView()

2020-09-18 13:24 UTC, gutachkee commented on src/main/java/com/example/test/MainActivity.java
> +        mSortButton.setOnClickListener(this);
initButtons()

2020-09-18 13:24 UTC, gutachkee commented on src/main/java/com/example/test/MainActivity.java
> +    };
Move to other fields declaration. (to the top of class body)

2020-09-18 13:24 UTC, gutachkee commented on src/main/java/com/example/test/MainActivity.java
> +            // 2. set it for the adapter
remove

2020-09-18 13:24 UTC, gutachkee commented on src/main/java/com/example/test/MainActivity.java
> +            // 2. check if mSortingMethod != null
remove

2020-09-18 13:24 UTC, gutachkee commented on src/main/java/com/example/test/MainActivity.java
> +            }
Consider this:
```suggestion
            if (mNumbersAdapter.getDataSet().length == 0) {
                // show error. (Toast, for example)
                return;
            }
            
            if (mSortingMethod == null) {
                // show error
                return;
            }
            
            mNumbersAdapter.setDataSet(mBinder.sort(mNumbersAdapter.getDataSet(), mSortingMethod));
```

Also, it would be even better to move out all this logic into onSortButtonClicked()

2020-09-18 13:24 UTC, gutachkee commented on src/main/java/com/example/test/MyService.java
>  public class MyService extends Service {
Give it concrete name. There should be no "MyService" name in production code.

2020-09-18 13:24 UTC, gutachkee commented on src/main/java/com/example/test/MyService.java
> +    private native int[] nativeGenerate(int count);
There is good practice to keep all native methods at the bottom of class body

2020-09-18 13:24 UTC, gutachkee commented on src/main/java/com/example/test/MyService.java
>      }
This can be removed. We use only bindService(), so we don't need this method override.

2020-09-18 13:24 UTC, gutachkee commented on src/main/java/com/example/test/MyService.java
>      }
It is redundant. Remove.

2020-09-18 13:24 UTC, gutachkee commented on src/main/java/com/example/test/MyService.java
> +    public class MyBinder extends Binder {
Concrete name.

2020-09-18 13:24 UTC, gutachkee commented on src/main/java/com/example/test/MyService.java
> +        }
Why do you need these methods? Should be removed.

2020-09-18 13:24 UTC, gutachkee commented on src/main/java/com/example/test/NumbersAdapter.java
> +    public NumbersAdapter(int numArray) {
Again: you don't need to pass length separately. What is the purpose of it? mNumArray will be overwritten in setDataSet(). Just init mNumArray with **new int[0]**.

2020-09-18 13:24 UTC, gutachkee commented on src/main/java/com/example/test/NumbersAdapter.java
> +    public NumbersViewHolder onCreateViewHolder(@NonNull ViewGroup parent, int viewType) {
If you are using @NonNull and @Nullable annotations - use it everywhere. It is a good practice.

2020-09-18 13:24 UTC, gutachkee commented on src/main/java/com/example/test/NumbersAdapter.java
> +        public void bind(int listIndex) {
nothing to do with index. It is our item's model. Use "model" or "value" name
```suggestion
        public void bind(int model) {
```

2020-09-18 13:24 UTC, gutachkee commented on src/main/java/com/example/test/sorters/Sorter.java
> +    enum SortingMethod { // binded with strings.xml for changes
Each item has own binding to string resource
```suggestion
    enum SortingMethod {
```

2020-09-18 13:24 UTC, gutachkee commented on src/main/java/com/example/test/sorters/Sorter.java
> +            return 0;
minor: to make sure that child class overrides this method, throw new AssertionError("getCaptionStringId() should be overriden!");
```suggestion
            throw new AssertionError("getCaptionStringId() should be overriden!");
            return 0;
```

2020-09-22 07:34 UTC, StanislavShchyrba commented on src/main/cpp/native-lib.cpp
> +    jint fill[count];
In generate() method I am not passing an array so i don't need to convert it by GetIntArrayElements(). Also i use SetIntArrayRegion() insted of ReleaseIntArrayElements(), by the situation where I don't have java array as parameter.

2020-09-22 08:05 UTC, StanislavShchyrba commented on src/main/java/com/example/test/MainActivity.java
> +        mSpinner.setOnItemSelectedListener(this);
Do you mean wrap in local function or rename comment?

2020-09-22 08:51 UTC, StanislavShchyrba commented on src/main/java/com/example/test/MainActivity.java
> +            }
mSortingMethod has dafault value and nowhere cannot be null. Should i overflow logic?

2020-09-22 10:03 UTC, gutachkee commented on src/main/cpp/native-lib.cpp
> +    jint fill[count];
The main point here is to use only one array. There is no need to create separate one here.

2020-09-22 10:04 UTC, gutachkee commented on src/main/java/com/example/test/MainActivity.java
> +        mSpinner.setOnItemSelectedListener(this);
wrap into a separate method

2020-09-22 10:13 UTC, gutachkee commented on src/main/java/com/example/test/MainActivity.java
> +            }
My change has identical logic as the previous code. There is no "overflow logic" there.

2020-09-24 09:05 UTC, gutachkee commented on src/androidTest/java/com/example/usage/ExampleInstrumentedTest.java
> +import static org.junit.Assert.assertEquals;
minor: these changes has nothing to do in this PR.

2020-09-24 10:28 UTC, gutachkee approved these changes
Everything is OK in general.
Just remove that unnecessary newlines.

2020-09-24 10:28 UTC, gutachkee commented on src/main/java/com/example/usage/NumbersAdapter.java
> +    private int[] mNumArray;
```suggestion
    @NonNull
    private int[] mNumArray;
```

2020-09-24 10:28 UTC, gutachkee commented on src/main/java/com/example/usage/SortService.java
> +    }
```suggestion
```

2020-09-24 10:28 UTC, gutachkee commented on src/main/java/com/example/usage/SortService.java
> +    private int[] nativeSort(@NonNull int[] array, @NonNull SortingMethod method) {
```suggestion
    private int[] sort(@NonNull int[] array, @NonNull SortingMethod method) {
```

2020-09-24 10:28 UTC, gutachkee commented on src/main/java/com/example/usage/SortingMethod.java
> +
```suggestion
```

2020-09-24 10:28 UTC, gutachkee commented on src/main/java/com/example/usage/sorters/Sorter.java
> +    int[] sort(int[] array);
```suggestion
    @NonNull
    int[] sort(@NonNull int[] array);
```

2020-09-24 14:14 UTC, merged