[rmp-2] SortServiceManager
StanislavShchyrba/Android-Servises pull request #3
Opened 2020-09-30 12:00 UTC by StanislavShchyrba

- Added manager to SortService

- Synchronized binding SortService

- Refactoring code(All exceptions handling carried over to manager)

2020-09-30 15:26 UTC, gutachkee requested changes
Better code quality. Good job. Keep going the good work.

few commens from me.

2020-09-30 15:26 UTC, gutachkee commented on src/androidTest/java/com/example/sortingapp/ExampleInstrumentedTest.java
> +>>>>>>> f4bf8bf4ddac0cce6586beaf5deb0b0e087e29a6:src/androidTest/java/com/example/usage/ExampleInstrumentedTest.java
?

2020-09-30 15:26 UTC, gutachkee commented on src/main/AndroidManifest.xml
> +    package="com.example.sortingapp">
:+1:

2020-09-30 15:26 UTC, gutachkee commented on src/main/cpp/generate.cpp
> +#include "generate.h"
better names: "num_generator.h", "generator.h"

2020-09-30 15:26 UTC, gutachkee commented on src/main/cpp/quicksort.h
> +    int partition(int arr[], int low, int high);
this method is unused outside. Shouldn't be defined here.

2020-09-30 15:26 UTC, gutachkee commented on src/main/java/com/example/sortingapp/MainActivity.java
> +            isStartedSuccesfully = mSortManager.bind(MainActivity.this);
isStartedSuccesfully is unused. Use it in onClick() method: if isStartedSuccesfully == false -> show toast error.

ps. consider this name: isServiceBoundSuccesfully or isServiceBound

2020-09-30 15:26 UTC, gutachkee commented on src/main/java/com/example/sortingapp/MainActivity.java
> +                R.string.service_binded, Toast.LENGTH_SHORT).show();
Service is not bound at this point. Binding is done async. Remove this or place it right after `isStartedSuccesfully = mSortManager.bind(MainActivity.this);` line.

ps. if you move this to other thread, do not forget to post the toast showing to UI thread:
`new Handler(Looper.getMainLooper()).post(() -> showToastMessage(isServiceBound));`

2020-09-30 15:26 UTC, gutachkee commented on src/main/java/com/example/sortingapp/MainActivity.java
> +        sortedNumbersArray = mSortManager.sort(mNumbersAdapter.getDataSet(), mSortingMethod);
make single line

2020-09-30 15:26 UTC, gutachkee commented on src/main/java/com/example/sortmanager/SortServiceManager.java
> +    private ISortService mSortService = null;
```suggestion
    private volatile ISortService mSortService = null;
```

Create Trello ticket with "Learn about volatile fields"

2020-09-30 15:26 UTC, gutachkee commented on src/test/java/com/example/sortingapp/ExampleUnitTest.java
> +>>>>>>> f4bf8bf4ddac0cce6586beaf5deb0b0e087e29a6:src/test/java/com/example/usage/ExampleUnitTest.java
Remove unresolved conflicts.

2020-09-30 15:26 UTC, gutachkee commented on src/test/java/com/example/usage/ExampleUnitTest.java
the same. remove.

2020-10-01 07:56 UTC, StanislavShchyrba commented on src/main/cpp/quicksort.h
> +    int partition(int arr[], int low, int high);
partition is used in quickSort method. Where should I locate this method, inner anonymous namespace?

2020-10-01 10:22 UTC, StanislavShchyrba reviewed
Reverted unnecessary changes in unit tests.

2020-10-06 05:41 UTC, gutachkee approved these changes

2020-10-06 09:12 UTC, merged